// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myAppService.API.Data;

namespace myAppService.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180728073017_initilaCreate")]
    partial class initilaCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("myAppService.API.models.Scheduler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArrivalTime");

                    b.Property<string>("DepartureTime");

                    b.Property<int>("TrainId");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("Schedulers");
                });

            modelBuilder.Entity("myAppService.API.models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FromLocation");

                    b.Property<string>("Name");

                    b.Property<DateTime>("ScheduledDate");

                    b.Property<string>("ToLocation");

                    b.HasKey("Id");

                    b.ToTable("Train");
                });

            modelBuilder.Entity("myAppService.API.models.Scheduler", b =>
                {
                    b.HasOne("myAppService.API.models.Train", "train")
                        .WithMany("lstScheduler")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
